### PR TITLE
fix menu background on non-scrollable page

### LINKED ISSUE #62: FICTO IMAGING - content disapears when clicked combined solutions
### Brief bug description

FICTO IMAGING - content disapears when clicked combined solutions 

### Repro steps

1. Go to 'https://ficto-imaging.sample.kontent.ai'
2. Click on 'Combined solutions'
3. See nothing

### Expected behavior

The content and website parts should be visible

### Test environment

 - Platform/OS: [e.g. .NET Core 2.1, iOS]

### Screenshots

image

### PR DESCRIPTION
**Pull request by IvanKiral**
### Motivation

Which issue does this fix? Fixes #62 

If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

### CODE REVIEW

File: components/shared/ui/menu.tsx [hunk 1]
```diff
@@ -147,11 +147,17 @@ export const Menu: FC<Props> = (props) => {
...
+  const router = useRouter();
 
   const handleMenuClick = (menuId: string | number): void => {
     setActiveMenu(menuId === activeMenu ? -1 : menuId);
   };
 
+  useEffect(() => {
+    // set is scrolled to show the menu when scrolling is not possible
+    setIsScrolled(document.body.scrollHeight <= window.innerHeight);
+  }, [router]);
```
Comment (JiriLojda) [inline components/shared/ui/menu.tsx:159]: Why do you need the router here? The component doesn't re-mount on navigating somewhere else? Also why do you use the whole `router` project as a dependency, isn't just the path property enough?

**Review by JiriLojda — CHANGES_REQUESTED** [review]

**Review by JiriLojda — APPROVED** [review]
